version: 1 
builder:   
  configs:
  - documentation_targets: [WrkstrmLog]
    custom_documentation_parameters: [--include-extended-types]
  - platform: watchos
    swift_version: '5.10'
  - platform: ios
    swift_version: '5.10'
  - platform: macos
    swift_version: '5.10'
  - platform: ipados
    swift_version: '5.10'
  - platform: linux
    swift_version: '5.10'
    image: registry.gitlab.com/finestructure/spi-images:AppKid-5.10-latest
