version: 1 
builder:   
  configs:
  - documentation_targets: [WrkstrmLog]
    custom_documentation_parameters: [--include-extended-types]
  - platform: watchos
    swift_version: '6.1'
  - platform: ios
    swift_version: '6.1'
  - platform: macos
    swift_version: '6.1'
  - platform: ipados
    swift_version: '6.1'
  - platform: linux
    swift_version: '6.1'
    image: registry.gitlab.com/finestructure/spi-images:AppKid-6.1-latest
