version: 1 
builder:   
  configs:
  - documentation_targets: [WrkstrmLog]
    custom_documentation_parameters: [--include-extended-types]
  - platform: watchos
    scheme: ComposableArchitecture_watchOS
  - platform: linux
    swift_version: '5.8'
    image: registry.gitlab.com/finestructure/spi-images:AppKid-5.8-latest
