name: Deploy DocC

on:
  push:
    branches: [ main ]

jobs:
  deploy_docs:
    strategy:
        matrix:
          os:
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-14' || matrix.os == 'self-hosted'
        with:
          xcode-version: '16.0.0-beta'
      - name: Build Documentation
        run: 'swift package --allow-writing-to-directory ./docs generate-documentation --target WrkstrmLog --output-path ./docs'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
