name: Deploy DocC

on:
  push:
    branches: [ main ]

jobs:
  deploy_docs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation --target SPMConfigSteward \
            --output-path ./docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
