name: Deploy DocC

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  create_docs:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Pages
        uses: actions/configure-pages@v5
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-15' || matrix.os == 'self-hosted'
        with:
          xcode-version: '26.0.0-beta'
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"
      - name: Generate Docs
        uses: fwcd/swift-docc-action@v1
        with:
          target: WrkstrmLog
          output: ./public
          transform-for-static-hosting: 'true'
          disable-indexing: 'false'
          hosting-base-path: wrkstrm-log
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: create_docs

    steps:
    - name: Deploy Docs
      id: deployment
      uses: actions/deploy-pages@v4
